-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function solution(num)
	local x = 1
	local y = 2
	local sum = 0

	while x < num do
		if x%2 == 0 then
			sum = sum + x
		end
		local z = x + y
		x,y = y,z
	end
	return sum
end

print(solution(10))
print(solution(4000000))
			
		
