--The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
--1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
--Let us list the factors of the first seven triangle numbers:
-- 1: 1
-- 3: 1,3
-- 6: 1,2,3,6
--10: 1,2,5,10
--15: 1,3,5,15
--21: 1,3,7,21
--28: 1,2,4,7,14,28
--We can see that 28 is the first triangle number to have over five divisors.
--What is the value of the first triangle number to have over five hundred divisors?

local function countDivisors(num)
	local count = 0
	local i   = 1
	local sqt = math.floor(math.sqrt(num))
	while i < sqt do
		if(num % i == 0) then count = count + 2 end
		i = i+1
	end
	if  sqt*sqt == num then count = count + 1 end
	return count
end

function solution(count)
	local num = 1
	for i = 2 ,math.pow(2, 54) do
		num = num + i
		if count < countDivisors(num) then return num end
	end
	return -1
end

print(solution(5))
print(solution(500))
	

		
